//
// Created by zhiwei.gong on 2026/5/12.
//

#ifndef STM32F4DISCOVERY_HAL_GPIO_H
#define STM32F4DISCOVERY_HAL_GPIO_H
#include "stdint.h"

/* 编码公式：(port)<<4) | (pin) */
//#define  AF_REQ_ENCODE(port, pin, mode)  (((port) << 4) | (pin))

/* 解码宏 */
//#define AF_REQ_GET_PORT(req)   ((req) >> 4 & 0x0F)
//#define AF_REQ_GET_PIN(req) ((req) & 0x0F)

/* 编码公式：((port)<<8) | ((pin)<<4) | (mode) */
#define  AF_REQ_ENCODE(port, pin, mode)  (((port) << 8) | ((pin) << 4) | (mode))

/* 解码宏 */
#define AF_REQ_GET_PORT(req)   ((req) >> 8 & 0x0F)
#define AF_REQ_GET_PIN(req) (((req) >> 4) & 0x0F)
#define AF_REQ_GET_MODE(req) ((req) & 0x0F)

/* GPIO 基址 */
#define xGPIOA_BASE 0x40020000UL
#define xGPIOB_BASE 0x40020400UL
#define xGPIOC_BASE 0x40020800UL
#define xGPIOD_BASE 0x40020C00UL
#define xGPIOE_BASE 0x40021000UL
#define xGPIOF_BASE 0x40021400UL
#define xGPIOG_BASE 0x40021800UL
#define xGPIOH_BASE 0x40021C00UL
#define xGPIOI_BASE 0x40022000UL

/* 端口枚举，顺序对应 RCC_AHB1ENR 的 bit 位 */
typedef enum : uint8_t {
    PORT_A = 0,
    PORT_B,
    PORT_C,
    PORT_D,
    PORT_E,
    PORT_F,
    PORT_G,
    PORT_H,
    PORT_I,
    PORT_MAX
} gpio_port_t;

typedef enum : uint8_t {
    PIN_0 = 0,
    PIN_1,
    PIN_2,
    PIN_3,
    PIN_4,
    PIN_5,
    PIN_6,
    PIN_7,
    PIN_8,
    PIN_9,
    PIN_10,
    PIN_11,
    PIN_12,
    PIN_13,
    PIN_14,
    PIN_15,
    PIN_MAX
} gpio_pin_t;

/* 工作模式 */
typedef enum : uint8_t {
    PIN_MODE_INPUT = 0x00,
    PIN_MODE_OUTPUT,
    PIN_MODE_AF,
    PIN_MODE_ANALOG
} pin_mode;
typedef enum : uint8_t {
    PIN_OTYPE_PP = 0, /* 推挽 */
    PIN_OTYPE_OD  /* 开漏 */
} pin_otype;
/* 输出速度 */
typedef enum : uint8_t {
    PIN_OSPEED_LOW = 0,
    PIN_OSPEED_MEDIUM,
    PIN_OSPEED_HIGH,
    PIN_OSPEED_VERY_HIGH
} pin_ospeed;

typedef enum :uint8_t {
    /* ========== 外设 AF 值宏定义（STM32F407） ========== */
    AF_SYSTEM   =  0,   /* MCO, JTAG/SWD, RTC, 事件输出等 */
    AF_MCO      =  0,
    AF_JTAG     =  0,
    AF_SWD      =  0,
    AF_RTC      =  0,
    AF_TRACE    =  0,
    AF_TIM1     =  1,
    AF_TIM2     =  1,
    AF_TIM3     =  2,
    AF_TIM4     =  2,
    AF_TIM5     =  2,
    AF_TIM8     =  3,
    AF_TIM9     =  3,
    AF_TIM10    =  3,
    AF_TIM11    =  3,
    AF_TIM12    =  9,   /* 注意：TIM12/13/14 的 AF 是 9 */
    AF_TIM13    =  9,
    AF_TIM14    =  9,
    AF_I2C1     =  4,
    AF_I2C2     =  4,
    AF_I2C3     =  4,
    AF_SPI1     =  5,
    AF_SPI2     =  5,
    AF_SPI3     =  6,   /* SPI3 常用 AF6，但也有少数引脚是 AF5，详见注 */
    AF_SPI3_ALT =  5,
    AF_I2S2     =  5,
    AF_I2S3     =  6,
    AF_USART1   =  7,
    AF_USART2   =  7,
    AF_USART3   =  7,
    AF_UART4    =  8,
    AF_UART5    =  8,
    AF_USART6   =  7,   /* USART6 也是 AF7 */
    AF_CAN1     =  9,
    AF_CAN2     =  9,
    AF_SDIO     =  12,
    AF_ETH      =  11,  /* 以太网 */
    AF_OTG_FS   =  10,  /* USB FS */
    AF_OTG_HS   =  10,  /* USB HS (ULPI) */
    AF_DCMI     =  13,  /* 数字摄像头接口 */
    AF_FSMC     =  12,  /* FSMC 与 SDIO 共用 AF12 */
    AF_EVENTOUT =  15,  /* 调试事件输出 */
    AF_NONE     =  16,
} pin_af_mode;


typedef enum : uint16_t {

    PA0_REQ_USART2_CTS       = AF_REQ_ENCODE(PORT_A, PIN_0, AF_USART2),
    PA0_REQ_UART4_TX         = AF_REQ_ENCODE(PORT_A, PIN_0, AF_UART4),
    PA0_REQ_ETH_MII_CRS      = AF_REQ_ENCODE(PORT_A, PIN_0, AF_ETH),
    PA0_REQ_TIM2_CH1_ETR     = AF_REQ_ENCODE(PORT_A, PIN_0, AF_TIM2),
    PA0_REQ_TIM5_CH1         = AF_REQ_ENCODE(PORT_A, PIN_0, AF_TIM5),
    PA0_REQ_TIM8_ETR         = AF_REQ_ENCODE(PORT_A, PIN_0, AF_TIM8),
    PA0_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_A, PIN_0, AF_EVENTOUT),

    PA1_REQ_USART2_RTS       = AF_REQ_ENCODE(PORT_A, PIN_1, AF_USART2),
    PA1_REQ_UART4_RX         = AF_REQ_ENCODE(PORT_A, PIN_1, AF_UART4),
    PA1_REQ_ETH_RMII_REF_CLK = AF_REQ_ENCODE(PORT_A, PIN_1, AF_ETH),
    PA1_REQ_ETH_MII_RX_CLK   = AF_REQ_ENCODE(PORT_A, PIN_1, AF_ETH),
    PA1_REQ_TIM5_CH2         = AF_REQ_ENCODE(PORT_A, PIN_1, AF_TIM5),
    PA1_REQ_TIM2_CH2         = AF_REQ_ENCODE(PORT_A, PIN_1, AF_TIM2),
    PA1_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_A, PIN_1, AF_EVENTOUT),


    PA2_REQ_USART2_TX        = AF_REQ_ENCODE(PORT_A, PIN_2, AF_USART2),
    PA2_REQ_TIM5_CH3         = AF_REQ_ENCODE(PORT_A, PIN_2, AF_TIM5),
    PA2_REQ_TIM9_CH1         = AF_REQ_ENCODE(PORT_A, PIN_2, AF_TIM9),
    PA2_REQ_TIM2_CH3         = AF_REQ_ENCODE(PORT_A, PIN_2, AF_TIM2),
    PA2_REQ_ETH_MDIO         = AF_REQ_ENCODE(PORT_A, PIN_2, AF_ETH),
    PA2_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_A, PIN_2, AF_EVENTOUT),

    PA3_REQ_USART2_RX        = AF_REQ_ENCODE(PORT_A, PIN_3, AF_USART2),
    PA3_REQ_TIM5_CH4         = AF_REQ_ENCODE(PORT_A, PIN_3, AF_TIM5),
    PA3_REQ_TIM9_CH2         = AF_REQ_ENCODE(PORT_A, PIN_3, AF_TIM9),
    PA3_REQ_TIM2_CH4         = AF_REQ_ENCODE(PORT_A, PIN_3, AF_TIM2),
    PA3_REQ_OTG_HS_ULPI_D0   = AF_REQ_ENCODE(PORT_A, PIN_3, AF_OTG_HS),
    PA3_REQ_ETH_MII_COL      = AF_REQ_ENCODE(PORT_A, PIN_3, AF_ETH),
    PA3_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_A, PIN_3, AF_EVENTOUT),

    PA4_REQ_SPI1_NSS         = AF_REQ_ENCODE(PORT_A, PIN_4, AF_SPI1),
    PA4_REQ_SPI3_NSS         = AF_REQ_ENCODE(PORT_A, PIN_4, AF_SPI3),
    PA4_REQ_USART2_CK        = AF_REQ_ENCODE(PORT_A, PIN_4, AF_USART2),
    PA4_REQ_DCMI_HSYNC       = AF_REQ_ENCODE(PORT_A, PIN_4, AF_DCMI),
    PA4_REQ_OTG_HS_SOF       = AF_REQ_ENCODE(PORT_A, PIN_4, AF_OTG_HS),
    PA4_REQ_I2S3_WS          = AF_REQ_ENCODE(PORT_A, PIN_4, AF_I2S3),
    PA4_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_A, PIN_4, AF_EVENTOUT),

    PA5_REQ_SPI1_SCK         = AF_REQ_ENCODE(PORT_A, PIN_5, AF_SPI1),
    PA5_REQ_OTG_HS_ULPI_CK   = AF_REQ_ENCODE(PORT_A, PIN_5, AF_OTG_HS),
    PA5_REQ_TIM2_CH1_ETR     = AF_REQ_ENCODE(PORT_A, PIN_5, AF_TIM2),
    PA5_REQ_TIM8_CH1N        = AF_REQ_ENCODE(PORT_A, PIN_5, AF_TIM8),
    PA5_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_A, PIN_5, AF_EVENTOUT),

    PA6_REQ_SPI1_MISO        = AF_REQ_ENCODE(PORT_A, PIN_6, AF_SPI1),
    PA6_REQ_TIM8_BKIN        = AF_REQ_ENCODE(PORT_A, PIN_6, AF_TIM8),
    PA6_REQ_TIM13_CH1        = AF_REQ_ENCODE(PORT_A, PIN_6, AF_TIM13),
    PA6_REQ_DCMI_PIXCLK      = AF_REQ_ENCODE(PORT_A, PIN_6, AF_DCMI),
    PA6_REQ_TIM3_CH1         = AF_REQ_ENCODE(PORT_A, PIN_6, AF_TIM3),
    PA6_REQ_TIM1_BKIN        = AF_REQ_ENCODE(PORT_A, PIN_6, AF_TIM1),
    PA6_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_A, PIN_6, AF_EVENTOUT),

    PA7_REQ_SPI1_MOSI        = AF_REQ_ENCODE(PORT_A, PIN_7, AF_SPI1),
    PA7_REQ_TIM8_CH1N        = AF_REQ_ENCODE(PORT_A, PIN_7, AF_TIM8),
    PA7_REQ_TIM14_CH1        = AF_REQ_ENCODE(PORT_A, PIN_7, AF_TIM14),
    PA7_REQ_TIM3_CH2         = AF_REQ_ENCODE(PORT_A, PIN_7, AF_TIM3),
    PA7_REQ_ETH_MII_RX_DV    = AF_REQ_ENCODE(PORT_A, PIN_7, AF_ETH),
    PA7_REQ_TIM1_CH1N        = AF_REQ_ENCODE(PORT_A, PIN_7, AF_TIM1),
    PA7_REQ_ETH_RMII_CRS_DV  = AF_REQ_ENCODE(PORT_A, PIN_7, AF_ETH),
    PA7_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_A, PIN_7, AF_EVENTOUT),

    PA8_REQ_MCO1            = AF_REQ_ENCODE(PORT_A, PIN_8, AF_MCO),
    PA8_REQ_USART1_CK       = AF_REQ_ENCODE(PORT_A, PIN_8, AF_USART1),
    PA8_REQ_TIM1_CH1        = AF_REQ_ENCODE(PORT_A, PIN_8, AF_TIM1),
    PA8_REQ_I2C3_SCL        = AF_REQ_ENCODE(PORT_A, PIN_8, AF_I2C3),
    PA8_REQ_OTG_FS_SOF      = AF_REQ_ENCODE(PORT_A, PIN_8, AF_OTG_FS),
    PA8_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_A, PIN_8, AF_EVENTOUT),

    PA9_REQ_USART1_TX       = AF_REQ_ENCODE(PORT_A, PIN_9, AF_USART1),
    PA9_REQ_TIM1_CH2        = AF_REQ_ENCODE(PORT_A, PIN_9, AF_TIM1),
    PA9_REQ_I2C3_SMBA       = AF_REQ_ENCODE(PORT_A, PIN_9, AF_I2C3),
    PA9_REQ_DCMI_D0         = AF_REQ_ENCODE(PORT_A, PIN_9, AF_DCMI),
    PA9_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_A, PIN_9, AF_EVENTOUT),

    PA10_REQ_USART1_RX      = AF_REQ_ENCODE(PORT_A, PIN_10, AF_USART1),
    PA10_REQ_TIM1_CH3       = AF_REQ_ENCODE(PORT_A, PIN_10, AF_TIM1),
    PA10_REQ_OTG_FS_ID      = AF_REQ_ENCODE(PORT_A, PIN_10, AF_OTG_FS),
    PA10_REQ_DCMI_D1        = AF_REQ_ENCODE(PORT_A, PIN_10, AF_DCMI),
    PA10_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_A, PIN_10, AF_EVENTOUT),

    PA11_REQ_USART1_CTS     = AF_REQ_ENCODE(PORT_A, PIN_11, AF_USART1),
    PA11_REQ_CAN1_RX        = AF_REQ_ENCODE(PORT_A, PIN_11, AF_CAN1),
    PA11_REQ_TIM1_CH4       = AF_REQ_ENCODE(PORT_A, PIN_11, AF_TIM1),
    PA11_REQ_OTG_FS_DM      = AF_REQ_ENCODE(PORT_A, PIN_11, AF_OTG_FS),
    PA11_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_A, PIN_11, AF_EVENTOUT),

    PA12_REQ_USART1_RTS     = AF_REQ_ENCODE(PORT_A, PIN_12, AF_USART1),
    PA12_REQ_CAN1_TX        = AF_REQ_ENCODE(PORT_A, PIN_12, AF_CAN1),
    PA12_REQ_TIM1_ETR       = AF_REQ_ENCODE(PORT_A, PIN_12, AF_TIM1),
    PA12_REQ_OTG_FS_DP      = AF_REQ_ENCODE(PORT_A, PIN_12, AF_OTG_FS),
    PA12_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_A, PIN_12, AF_EVENTOUT),

    PA13_REQ_SWD_SWDIO       = AF_REQ_ENCODE(PORT_A, PIN_13, AF_SWD),
    PA13_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_A, PIN_13, AF_EVENTOUT),

    PA14_REQ_SWD_SWCLK       = AF_REQ_ENCODE(PORT_A, PIN_14, AF_SWD),
    PA14_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_A, PIN_14, AF_EVENTOUT),

    PA15_REQ_JTAG_JTDI       = AF_REQ_ENCODE(PORT_A, PIN_15, AF_JTAG),
    PA15_REQ_SPI3_NSS        = AF_REQ_ENCODE(PORT_A, PIN_15, AF_SPI3),
    PA15_REQ_I2S3_WS         = AF_REQ_ENCODE(PORT_A, PIN_15, AF_I2C3),
    PA15_REQ_TIM2_CH1_ETR    = AF_REQ_ENCODE(PORT_A, PIN_15, AF_TIM2),
    PA15_REQ_SPI1_NSS        = AF_REQ_ENCODE(PORT_A, PIN_15, AF_SPI1),
    PA15_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_A, PIN_15, AF_EVENTOUT),

    PB0_REQ_TIM3_CH3         = AF_REQ_ENCODE(PORT_B, PIN_0, AF_TIM3),
    PB0_REQ_TIM8_CH2N        = AF_REQ_ENCODE(PORT_B, PIN_0, AF_TIM8),
    PB0_REQ_OTG_HS_ULPI_D1   = AF_REQ_ENCODE(PORT_B, PIN_0, AF_OTG_HS),
    PB0_REQ_ETH_MII_RXD2     = AF_REQ_ENCODE(PORT_B, PIN_0, AF_ETH),
    PB0_REQ_TIM1_CH2N        = AF_REQ_ENCODE(PORT_B, PIN_0, AF_TIM1),
    PB0_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_B, PIN_0, AF_EVENTOUT),

    PB1_REQ_TIM3_CH4         = AF_REQ_ENCODE(PORT_B, PIN_1, AF_TIM3),
    PB1_REQ_TIM8_CH3N        = AF_REQ_ENCODE(PORT_B, PIN_1, AF_TIM8),
    PB1_REQ_OTG_HS_ULPI_D2   = AF_REQ_ENCODE(PORT_B, PIN_1, AF_OTG_HS),
    PB1_REQ_ETH_MII_RXD3     = AF_REQ_ENCODE(PORT_B, PIN_1, AF_ETH),
    PB1_REQ_TIM1_CH3N        = AF_REQ_ENCODE(PORT_B, PIN_1, AF_TIM1),
    PB1_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_B, PIN_1, AF_EVENTOUT),

    PB2_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_B, PIN_2, AF_EVENTOUT),

    PB3_REQ_JTAG_JTDO        = AF_REQ_ENCODE(PORT_B, PIN_3, AF_JTAG),
    PB3_REQ_TRACE_SWO        = AF_REQ_ENCODE(PORT_B, PIN_3, AF_TRACE),
    PB3_REQ_SPI3_SCK         = AF_REQ_ENCODE(PORT_B, PIN_3, AF_SPI3),
    PB3_REQ_I2S3_CK          = AF_REQ_ENCODE(PORT_B, PIN_3, AF_I2S3),
    PB3_REQ_TIM2_CH2         = AF_REQ_ENCODE(PORT_B, PIN_3, AF_TIM2),
    PB3_REQ_SPI1_SCK         = AF_REQ_ENCODE(PORT_B, PIN_3, AF_SPI1),
    PB3_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_B, PIN_3, AF_EVENTOUT),

    PB4_REQ_JTAG_NJTRST      = AF_REQ_ENCODE(PORT_B, PIN_4, AF_JTAG),
    PB4_REQ_SPI3_MISO        = AF_REQ_ENCODE(PORT_B, PIN_4, AF_SPI3),
    PB4_REQ_TIM3_CH1         = AF_REQ_ENCODE(PORT_B, PIN_4, AF_TIM3),
    PB4_REQ_SPI1_MISO        = AF_REQ_ENCODE(PORT_B, PIN_4, AF_SPI1),
    PB4_REQ_I2S3ext_SD       = AF_REQ_ENCODE(PORT_B, PIN_4, AF_I2S3),
    PB4_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_B, PIN_4, AF_EVENTOUT),

    PB5_REQ_I2C1_SMBA        = AF_REQ_ENCODE(PORT_B, PIN_5, AF_I2C1),
    PB5_REQ_CAN2_RX          = AF_REQ_ENCODE(PORT_B, PIN_5, AF_CAN2),
    PB5_REQ_OTG_HS_ULPI_D7   = AF_REQ_ENCODE(PORT_B, PIN_5, AF_OTG_HS),
    PB5_REQ_ETH_PPS_OUT      = AF_REQ_ENCODE(PORT_B, PIN_5, AF_ETH),
    PB5_REQ_TIM3_CH2         = AF_REQ_ENCODE(PORT_B, PIN_5, AF_TIM3),
    PB5_REQ_SPI1_MOSI        = AF_REQ_ENCODE(PORT_B, PIN_5, AF_SPI1),
    PB5_REQ_SPI3_MOSI        = AF_REQ_ENCODE(PORT_B, PIN_5, AF_SPI3),
    PB5_REQ_DCMI_D10         = AF_REQ_ENCODE(PORT_B, PIN_5, AF_DCMI),
    PB5_REQ_I2S3_SD          = AF_REQ_ENCODE(PORT_B, PIN_5, AF_I2S3),
    PB5_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_B, PIN_5, AF_EVENTOUT),

    PB6_REQ_I2C1_SCL         = AF_REQ_ENCODE(PORT_B, PIN_6, AF_I2C1),
    PB6_REQ_TIM4_CH1         = AF_REQ_ENCODE(PORT_B, PIN_6, AF_TIM4),
    PB6_REQ_CAN2_TX          = AF_REQ_ENCODE(PORT_B, PIN_6, AF_CAN2),
    PB6_REQ_DCMI_D5          = AF_REQ_ENCODE(PORT_B, PIN_6, AF_DCMI),
    PB6_REQ_USART1_TX        = AF_REQ_ENCODE(PORT_B, PIN_6, AF_USART1),
    PB6_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_B, PIN_6, AF_EVENTOUT),

    PB7_REQ_I2C1_SDA         = AF_REQ_ENCODE(PORT_B, PIN_7, AF_I2C1),
    PB7_REQ_FSMC_NL          = AF_REQ_ENCODE(PORT_B, PIN_7, AF_FSMC),
    PB7_REQ_DCMI_VSYNC       = AF_REQ_ENCODE(PORT_B, PIN_7, AF_DCMI),
    PB7_REQ_USART1_RX        = AF_REQ_ENCODE(PORT_B, PIN_7, AF_USART1),
    PB7_REQ_TIM4_CH2         = AF_REQ_ENCODE(PORT_B, PIN_7, AF_TIM4),
    PB7_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_B, PIN_7, AF_EVENTOUT),

    PB8_REQ_TIM4_CH3         = AF_REQ_ENCODE(PORT_B, PIN_8, AF_TIM4),
    PB8_REQ_SDIO_D4          = AF_REQ_ENCODE(PORT_B, PIN_8, AF_SDIO),
    PB8_REQ_TIM10_CH1        = AF_REQ_ENCODE(PORT_B, PIN_8, AF_TIM10),
    PB8_REQ_DCMI_D6          = AF_REQ_ENCODE(PORT_B, PIN_8, AF_DCMI),
    PB8_REQ_ETH_MII_TXD3     = AF_REQ_ENCODE(PORT_B, PIN_8, AF_ETH),
    PB8_REQ_I2C1_SCL         = AF_REQ_ENCODE(PORT_B, PIN_8, AF_I2C1),
    PB8_REQ_CAN1_RX          = AF_REQ_ENCODE(PORT_B, PIN_8, AF_CAN1),
    PB8_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_B, PIN_8, AF_EVENTOUT),

    PB9_REQ_SPI2_NSS         = AF_REQ_ENCODE(PORT_B, PIN_9, AF_SPI2),
    PB9_REQ_I2S2_WS          = AF_REQ_ENCODE(PORT_B, PIN_9, AF_I2S2),
    PB9_REQ_TIM4_CH4         = AF_REQ_ENCODE(PORT_B, PIN_9, AF_TIM4),
    PB9_REQ_TIM11_CH1        = AF_REQ_ENCODE(PORT_B, PIN_9, AF_TIM11),
    PB9_REQ_SDIO_D5          = AF_REQ_ENCODE(PORT_B, PIN_9, AF_SDIO),
    PB9_REQ_DCMI_D7          = AF_REQ_ENCODE(PORT_B, PIN_9, AF_DCMI),
    PB9_REQ_I2C1_SDA         = AF_REQ_ENCODE(PORT_B, PIN_9, AF_I2C1),
    PB9_REQ_CAN1_TX          = AF_REQ_ENCODE(PORT_B, PIN_9, AF_CAN1),
    PB9_REQ_EVENTOUT         = AF_REQ_ENCODE(PORT_B, PIN_9, AF_EVENTOUT),

    PB10_REQ_SPI2_SCK       = AF_REQ_ENCODE(PORT_B, PIN_10, AF_SPI2),
    PB10_REQ_I2S2_CK        = AF_REQ_ENCODE(PORT_B, PIN_10, AF_I2S2),
    PB10_REQ_I2C2_SCL       = AF_REQ_ENCODE(PORT_B, PIN_10, AF_I2C2),
    PB10_REQ_USART3_TX      = AF_REQ_ENCODE(PORT_B, PIN_10, AF_USART3),
    PB10_REQ_OTG_HS_ULPI_D3 = AF_REQ_ENCODE(PORT_B, PIN_10, AF_OTG_HS),
    PB10_REQ_ETH_MII_RX_ER  = AF_REQ_ENCODE(PORT_B, PIN_10, AF_ETH),
    PB10_REQ_TIM2_CH3       = AF_REQ_ENCODE(PORT_B, PIN_10, AF_TIM2),
    PB10_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_B, PIN_10, AF_EVENTOUT),

    PB11_REQ_I2C2_SDA        = AF_REQ_ENCODE(PORT_B, PIN_11, AF_I2C2),
    PB11_REQ_USART3_RX       = AF_REQ_ENCODE(PORT_B, PIN_11, AF_USART3),
    PB11_REQ_OTG_HS_ULPI_D4  = AF_REQ_ENCODE(PORT_B, PIN_11, AF_OTG_HS),
    PB11_REQ_ETH_RMII_TX_EN  = AF_REQ_ENCODE(PORT_B, PIN_11, AF_ETH),
    PB11_REQ_ETH_MII_TX_EN   = AF_REQ_ENCODE(PORT_B, PIN_11, AF_ETH),
    PB11_REQ_TIM2_CH4        = AF_REQ_ENCODE(PORT_B, PIN_11, AF_TIM2),
    PB11_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_B, PIN_11, AF_EVENTOUT),

    PB12_REQ_SPI2_NSS        = AF_REQ_ENCODE(PORT_B, PIN_12, AF_SPI2),
    PB12_REQ_I2S2_WS         = AF_REQ_ENCODE(PORT_B, PIN_12, AF_I2S2),
    PB12_REQ_I2C2_SMBA       = AF_REQ_ENCODE(PORT_B, PIN_12, AF_I2C2),
    PB12_REQ_USART3_CK       = AF_REQ_ENCODE(PORT_B, PIN_12, AF_USART3),
    PB12_REQ_TIM1_BKIN       = AF_REQ_ENCODE(PORT_B, PIN_12, AF_TIM1),
    PB12_REQ_CAN2_RX         = AF_REQ_ENCODE(PORT_B, PIN_12, AF_CAN2),
    PB12_REQ_OTG_HS_ULPI_D5  = AF_REQ_ENCODE(PORT_B, PIN_12, AF_OTG_HS),
    PB12_REQ_ETH_RMII_TXD0   = AF_REQ_ENCODE(PORT_B, PIN_12, AF_ETH),
    PB12_REQ_ETH_MII_TXD0    = AF_REQ_ENCODE(PORT_B, PIN_12, AF_ETH),
    PB12_REQ_OTG_HS_ID       = AF_REQ_ENCODE(PORT_B, PIN_12, AF_OTG_HS),
    PB12_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_B, PIN_12, AF_EVENTOUT),

    PB13_REQ_SPI2_SCK       = AF_REQ_ENCODE(PORT_B, PIN_13, AF_SPI2),
    PB13_REQ_I2S2_CK        = AF_REQ_ENCODE(PORT_B, PIN_13, AF_I2S2),
    PB13_REQ_USART3_CTS     = AF_REQ_ENCODE(PORT_B, PIN_13, AF_USART3),
    PB13_REQ_TIM1_CH1N      = AF_REQ_ENCODE(PORT_B, PIN_13, AF_TIM1),
    PB13_REQ_CAN2_TX        = AF_REQ_ENCODE(PORT_B, PIN_13, AF_CAN2),
    PB13_REQ_OTG_HS_ULPI_D6 = AF_REQ_ENCODE(PORT_B, PIN_13, AF_OTG_HS),
    PB13_REQ_ETH_RMII_TXD1  = AF_REQ_ENCODE(PORT_B, PIN_13, AF_ETH),
    PB13_REQ_ETH_MII_TXD1   = AF_REQ_ENCODE(PORT_B, PIN_13, AF_ETH),
    PB13_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_B, PIN_13, AF_EVENTOUT),

    PB14_REQ_SPI2_MISO      = AF_REQ_ENCODE(PORT_B, PIN_14, AF_SPI2),
    PB14_REQ_TIM1_CH2N      = AF_REQ_ENCODE(PORT_B, PIN_14, AF_TIM1),
    PB14_REQ_TIM12_CH1      = AF_REQ_ENCODE(PORT_B, PIN_14, AF_TIM12),
    PB14_REQ_OTG_HS_DM      = AF_REQ_ENCODE(PORT_B, PIN_14, AF_OTG_HS),
    PB14_REQ_USART3_RTS     = AF_REQ_ENCODE(PORT_B, PIN_14, AF_USART3),
    PB14_REQ_TIM8_CH2N      = AF_REQ_ENCODE(PORT_B, PIN_14, AF_TIM8),
    PB14_REQ_I2S2ext_SD     = AF_REQ_ENCODE(PORT_B, PIN_14, AF_I2S2),
    PB14_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_B, PIN_14, AF_EVENTOUT),

    PB15_REQ_SPI2_MOSI      = AF_REQ_ENCODE(PORT_B, PIN_15, AF_SPI2),
    PB15_REQ_I2S2_SD        = AF_REQ_ENCODE(PORT_B, PIN_15, AF_I2S2),
    PB15_REQ_TIM1_CH3N      = AF_REQ_ENCODE(PORT_B, PIN_15, AF_TIM1),
    PB15_REQ_TIM8_CH3N      = AF_REQ_ENCODE(PORT_B, PIN_15, AF_TIM8),
    PB15_REQ_TIM12_CH2      = AF_REQ_ENCODE(PORT_B, PIN_15, AF_TIM12),
    PB15_REQ_OTG_HS_DP      = AF_REQ_ENCODE(PORT_B, PIN_15, AF_OTG_HS),
    PB15_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_B, PIN_15, AF_EVENTOUT),

    PC0_REQ_OTG_HS_ULPI_STP = AF_REQ_ENCODE(PORT_C, PIN_0, AF_OTG_HS),
    PC0_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_C, PIN_0, AF_EVENTOUT),

    PC1_REQ_ETH_MDC         = AF_REQ_ENCODE(PORT_C, PIN_1, AF_ETH),
    PC1_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_C, PIN_1, AF_EVENTOUT),

    PC2_REQ_SPI2_MISO       = AF_REQ_ENCODE(PORT_C, PIN_2, AF_SPI2),
    PC2_REQ_OTG_HS_ULPI_DIR = AF_REQ_ENCODE(PORT_C, PIN_2, AF_OTG_HS),
    PC2_REQ_ETH_MII_TXD2    = AF_REQ_ENCODE(PORT_C, PIN_2, AF_ETH),
    PC2_REQ_I2S2Ext_SD      = AF_REQ_ENCODE(PORT_C, PIN_2, AF_I2S2),
    PC2_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_C, PIN_2, AF_EVENTOUT),

    PC3_REQ_SPI2_MOSI       = AF_REQ_ENCODE(PORT_C, PIN_3, AF_SPI2),
    PC3_REQ_I2S2_SD         = AF_REQ_ENCODE(PORT_C, PIN_3, AF_I2S2),
    PC3_REQ_OTG_HS_ULPI_NXT = AF_REQ_ENCODE(PORT_C, PIN_3, AF_OTG_HS),
    PC3_REQ_ETH_MII_TX_CLK  = AF_REQ_ENCODE(PORT_C, PIN_3, AF_ETH),
    PC3_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_C, PIN_3, AF_EVENTOUT),

    PC4_REQ_ETH_RMII_RX_D0  = AF_REQ_ENCODE(PORT_C, PIN_4, AF_ETH),
    PC4_REQ_ETH_MII_RX_D0   = AF_REQ_ENCODE(PORT_C, PIN_4, AF_ETH),
    PC4_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_C, PIN_4, AF_EVENTOUT),

    PC5_REQ_ETH_RMII_RX_D1  = AF_REQ_ENCODE(PORT_C, PIN_5, AF_ETH),
    PC5_REQ_ETH_MII_RX_D1   = AF_REQ_ENCODE(PORT_C, PIN_5, AF_ETH),
    PC5_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_C, PIN_5, AF_EVENTOUT),

    PC6_REQ_I2S2_MCK         = AF_REQ_ENCODE(PORT_C, PIN_6, AF_I2S2),
    PC6_REQ_TIM8_CH1         = AF_REQ_ENCODE(PORT_C, PIN_6, AF_TIM8),
    PC6_REQ_SDIO_D6          = AF_REQ_ENCODE(PORT_C, PIN_6, AF_SDIO),
    PC6_REQ_USART6_TX        = AF_REQ_ENCODE(PORT_C, PIN_6, AF_USART6),
    PC6_REQ_DCMI_D0          = AF_REQ_ENCODE(PORT_C, PIN_6, AF_DCMI),
    PC6_REQ_TIM3_CH1         = AF_REQ_ENCODE(PORT_C, PIN_6, AF_TIM3),
    PC6_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_C, PIN_6, AF_EVENTOUT),

    PC7_REQ_I2S3_MCK         = AF_REQ_ENCODE(PORT_C, PIN_7, AF_I2S3),
    PC7_REQ_TIM8_CH2         = AF_REQ_ENCODE(PORT_C, PIN_7, AF_TIM8),
    PC7_REQ_SDIO_D7          = AF_REQ_ENCODE(PORT_C, PIN_7, AF_SDIO),
    PC7_REQ_USART6_RX        = AF_REQ_ENCODE(PORT_C, PIN_7, AF_USART6),
    PC7_REQ_DCMI_D1          = AF_REQ_ENCODE(PORT_C, PIN_7, AF_DCMI),
    PC7_REQ_TIM3_CH2         = AF_REQ_ENCODE(PORT_C, PIN_7, AF_TIM3),
    PC7_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_C, PIN_7, AF_EVENTOUT),

    PC8_REQ_TIM8_CH3         = AF_REQ_ENCODE(PORT_C, PIN_8, AF_TIM8),
    PC8_REQ_SDIO_D0          = AF_REQ_ENCODE(PORT_C, PIN_8, AF_SDIO),
    PC8_REQ_TIM3_CH3         = AF_REQ_ENCODE(PORT_C, PIN_8, AF_TIM3),
    PC8_REQ_USART6_CK        = AF_REQ_ENCODE(PORT_C, PIN_8, AF_USART3),
    PC8_REQ_DCMI_D2          = AF_REQ_ENCODE(PORT_C, PIN_8, AF_DCMI ),
    PC8_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_C, PIN_8, AF_EVENTOUT),

    PC9_REQ_I2S_CKIN         = AF_REQ_ENCODE(PORT_C, PIN_9, AF_I2S2),
    PC9_REQ_MCO2             = AF_REQ_ENCODE(PORT_C, PIN_9, AF_MCO),
    PC9_REQ_TIM8_CH4         = AF_REQ_ENCODE(PORT_C, PIN_9, AF_TIM8),
    PC9_REQ_SDIO_D1          = AF_REQ_ENCODE(PORT_C, PIN_9, AF_SDIO),
    PC9_REQ_I2C3_SDA         = AF_REQ_ENCODE(PORT_C, PIN_9, AF_I2C3),
    PC9_REQ_DCMI_D3          = AF_REQ_ENCODE(PORT_C, PIN_9, AF_DCMI),
    PC9_REQ_TIM3_CH4         = AF_REQ_ENCODE(PORT_C, PIN_9, AF_TIM3),
    PC9_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_C, PIN_9, AF_EVENTOUT),

    PC10_REQ_SPI3_SCK        = AF_REQ_ENCODE(PORT_C, PIN_10, AF_SPI3),
    PC10_REQ_I2S3_CK         = AF_REQ_ENCODE(PORT_C, PIN_10, AF_I2S3),
    PC10_REQ_UART4_TX        = AF_REQ_ENCODE(PORT_C, PIN_10, AF_UART4),
    PC10_REQ_SDIO_D2         = AF_REQ_ENCODE(PORT_C, PIN_10, AF_SDIO),
    PC10_REQ_DCMI_D8         = AF_REQ_ENCODE(PORT_C, PIN_10, AF_DCMI),
    PC10_REQ_USART3_TX       = AF_REQ_ENCODE(PORT_C, PIN_10, AF_USART3),
    PC10_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_C, PIN_10, AF_EVENTOUT),

    PC11_REQ_UART4_RX        = AF_REQ_ENCODE(PORT_C, PIN_11, AF_UART4),
    PC11_REQ_SPI3_MISO       = AF_REQ_ENCODE(PORT_C, PIN_11, AF_SPI3),
    PC11_REQ_SDIO_D3         = AF_REQ_ENCODE(PORT_C, PIN_11, AF_SDIO),
    PC11_REQ_DCMI_D4         = AF_REQ_ENCODE(PORT_C, PIN_11, AF_DCMI),
    PC11_REQ_USART3_RX       = AF_REQ_ENCODE(PORT_C, PIN_11, AF_USART3),
    PC11_REQ_I2S3ext_SD      = AF_REQ_ENCODE(PORT_C, PIN_11, AF_I2S3),
    PC11_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_C, PIN_11, AF_EVENTOUT),

    PC12_REQ_UART5_TX        = AF_REQ_ENCODE(PORT_C, PIN_12, AF_UART5),
    PC12_REQ_SDIO_CK         = AF_REQ_ENCODE(PORT_C, PIN_12, AF_SDIO),
    PC12_REQ_DCMI_D9         = AF_REQ_ENCODE(PORT_C, PIN_12, AF_DCMI),
    PC12_REQ_SPI3_MOSI       = AF_REQ_ENCODE(PORT_C, PIN_12, AF_SPI3),
    PC12_REQ_I2S3_SD         = AF_REQ_ENCODE(PORT_C, PIN_12, AF_I2S3),
    PC12_REQ_USART3_CK       = AF_REQ_ENCODE(PORT_C, PIN_12, AF_USART3),
    PC12_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_C, PIN_12, AF_EVENTOUT),
    //PC13  no AF
    //PC14  no AF
    //PC15  no AF

    PD0_REQ_FSMC_D2         = AF_REQ_ENCODE(PORT_D, PIN_0, AF_FSMC),
    PD0_REQ_CAN1_RX         = AF_REQ_ENCODE(PORT_D, PIN_0, AF_CAN1),
    PD0_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_D, PIN_0, AF_EVENTOUT),

    PD1_REQ_FSMC_D3         = AF_REQ_ENCODE(PORT_D, PIN_1, AF_FSMC),
    PD1_REQ_CAN1_TX         = AF_REQ_ENCODE(PORT_D, PIN_1, AF_CAN1),
    PD1_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_D, PIN_1, AF_EVENTOUT),

    PD2_REQ_TIM3_ETR        = AF_REQ_ENCODE(PORT_D, PIN_2, AF_TIM3),
    PD2_REQ_UART5_RX        = AF_REQ_ENCODE(PORT_D, PIN_2, AF_UART5),
    PD2_REQ_SDIO_CMD        = AF_REQ_ENCODE(PORT_D, PIN_2, AF_SDIO),
    PD2_REQ_DCMI_D11        = AF_REQ_ENCODE(PORT_D, PIN_2, AF_DCMI),
    PD2_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_D, PIN_2, AF_EVENTOUT),

    PD3_REQ_FSMC_CLK        = AF_REQ_ENCODE(PORT_D, PIN_3, AF_FSMC),
    PD3_REQ_USART2_CTS      = AF_REQ_ENCODE(PORT_D, PIN_3, AF_USART2),
    PD3_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_D, PIN_3, AF_EVENTOUT),

    PD4_REQ_FSMC_NOE        = AF_REQ_ENCODE(PORT_D, PIN_4, AF_FSMC),
    PD4_REQ_USART2_RTS      = AF_REQ_ENCODE(PORT_D, PIN_4, AF_USART2),
    PD4_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_D, PIN_4, AF_EVENTOUT),

    PD5_REQ_FSMC_NWE        = AF_REQ_ENCODE(PORT_D, PIN_5, AF_FSMC),
    PD5_REQ_USART2_TX       = AF_REQ_ENCODE(PORT_D, PIN_5, AF_USART2),
    PD5_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_D, PIN_5, AF_EVENTOUT),

    PD6_REQ_FSMC_NWAIT      = AF_REQ_ENCODE(PORT_D, PIN_6, AF_FSMC),
    PD6_REQ_USART2_RX       = AF_REQ_ENCODE(PORT_D, PIN_6, AF_USART2),
    PD6_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_D, PIN_6, AF_EVENTOUT),

    PD7_REQ_USART2_CK       = AF_REQ_ENCODE(PORT_D, PIN_7, AF_USART2),
    PD7_REQ_FSMC_NE1        = AF_REQ_ENCODE(PORT_D, PIN_7, AF_FSMC),
    PD7_REQ_FSMC_NCE2       = AF_REQ_ENCODE(PORT_D, PIN_7, AF_FSMC),
    PD7_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_D, PIN_7, AF_EVENTOUT),

    PD8_REQ_FSMC_D13        = AF_REQ_ENCODE(PORT_D, PIN_8, AF_FSMC),
    PD8_REQ_USART3_TX       = AF_REQ_ENCODE(PORT_D, PIN_8, AF_USART3),
    PD8_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_D, PIN_8, AF_EVENTOUT),

    PD9_REQ_FSMC_D14        = AF_REQ_ENCODE(PORT_D, PIN_9, AF_FSMC),
    PD9_REQ_USART3_RX       = AF_REQ_ENCODE(PORT_D, PIN_9, AF_USART3),
    PD9_REQ_EVENTOUT        = AF_REQ_ENCODE(PORT_D, PIN_9, AF_EVENTOUT),

    PD10_REQ_FSMC_D15       = AF_REQ_ENCODE(PORT_D, PIN_10, AF_FSMC),
    PD10_REQ_USART3_CK      = AF_REQ_ENCODE(PORT_D, PIN_10, AF_USART3),
    PD10_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_D, PIN_10, AF_EVENTOUT),

    PD11_REQ_FSMC_CLE       = AF_REQ_ENCODE(PORT_D, PIN_11, AF_FSMC),
    PD11_REQ_FSMC_A16       = AF_REQ_ENCODE(PORT_D, PIN_11, AF_FSMC),
    PD11_REQ_USART3_CTS     = AF_REQ_ENCODE(PORT_D, PIN_11, AF_USART3),
    PD11_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_D, PIN_11, AF_EVENTOUT),

    PD12_REQ_FSMC_ALE       = AF_REQ_ENCODE(PORT_D, PIN_12, AF_FSMC),
    PD12_REQ_FSMC_A17       = AF_REQ_ENCODE(PORT_D, PIN_12, AF_FSMC),
    PD12_REQ_TIM4_CH1       = AF_REQ_ENCODE(PORT_D, PIN_12, AF_TIM4),
    PD12_REQ_USART3_RTS     = AF_REQ_ENCODE(PORT_D, PIN_12, AF_USART3),
    PD12_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_D, PIN_12, AF_EVENTOUT),

    PD13_REQ_FSMC_A18       = AF_REQ_ENCODE(PORT_D, PIN_13, AF_FSMC),
    PD13_REQ_TIM4_CH2       = AF_REQ_ENCODE(PORT_D, PIN_13, AF_TIM4),
    PD13_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_D, PIN_13, AF_EVENTOUT),

    PD14_REQ_FSMC_D0        = AF_REQ_ENCODE(PORT_D, PIN_14, AF_FSMC),
    PD14_REQ_TIM4_CH3       = AF_REQ_ENCODE(PORT_D, PIN_14, AF_TIM4),
    PD14_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_D, PIN_14, AF_EVENTOUT),

    PD15_REQ_FSMC_D1        = AF_REQ_ENCODE(PORT_D, PIN_15, AF_FSMC),
    PD15_REQ_TIM4_CH4       = AF_REQ_ENCODE(PORT_D, PIN_15, AF_TIM4),
    PD15_REQ_EVENTOUT       = AF_REQ_ENCODE(PORT_D, PIN_15, AF_EVENTOUT),

    PE0_REQ_TIM4_ETR        = AF_REQ_ENCODE(PORT_E, PIN_0, AF_TIM4),
    PE0_REQ_FSMC_NBL0       = AF_REQ_ENCODE(PORT_E, PIN_0, AF_FSMC),
    PE0_REQ_DCMI_D2         = AF_REQ_ENCODE(PORT_E, PIN_0, AF_DCMI),
    PE0_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_0, AF_EVENTOUT),

    PE1_REQ_FSMC_NBL1       = AF_REQ_ENCODE(PORT_E, PIN_1, AF_FSMC),
    PE1_REQ_DCMI_D3         = AF_REQ_ENCODE(PORT_E, PIN_1, AF_DCMI),
    PE1_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_1, AF_EVENTOUT),

    PE2_REQ_TRACE_CLK       = AF_REQ_ENCODE(PORT_E, PIN_2, AF_TRACE),
    PE2_REQ_FSMC_A23        = AF_REQ_ENCODE(PORT_E, PIN_2, AF_FSMC),
    PE2_REQ_ETH_MII_TD3     = AF_REQ_ENCODE(PORT_E, PIN_2, AF_ETH),
    PE2_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_2, AF_EVENTOUT),

    PE3_REQ_TRACE_D0        = AF_REQ_ENCODE(PORT_E, PIN_3, AF_TRACE),
    PE3_REQ_FSMC_A19        = AF_REQ_ENCODE(PORT_E, PIN_3, AF_FSMC),
    PE3_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_3, AF_EVENTOUT),

    PE4_REQ_TRACE_D1        = AF_REQ_ENCODE(PORT_E, PIN_4, AF_TRACE),
    PE4_REQ_FSMC_A20        = AF_REQ_ENCODE(PORT_E, PIN_4, AF_FSMC),
    PE4_REQ_ETH_MII_TD4     = AF_REQ_ENCODE(PORT_E, PIN_4, AF_ETH),
    PE4_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_4, AF_EVENTOUT),

    PE5_REQ_TRACE_D2        = AF_REQ_ENCODE(PORT_E, PIN_5, AF_TRACE),
    PE5_REQ_FSMC_A21        = AF_REQ_ENCODE(PORT_E, PIN_5, AF_FSMC),
    PE5_REQ_TIM9_CH1        = AF_REQ_ENCODE(PORT_E, PIN_5, AF_TIM9),
    PE5_REQ_DCMI_D6         = AF_REQ_ENCODE(PORT_E, PIN_5, AF_DCMI),
    PE5_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_5, AF_EVENTOUT),

    PE6_REQ_TRACE_D3        = AF_REQ_ENCODE(PORT_E, PIN_6, AF_TRACE),
    PE6_REQ_FSMC_A22        = AF_REQ_ENCODE(PORT_E, PIN_6, AF_FSMC),
    PE6_REQ_TIM9_CH2        = AF_REQ_ENCODE(PORT_E, PIN_6, AF_TIM9),
    PE6_REQ_DCMI_D7         = AF_REQ_ENCODE(PORT_E, PIN_6, AF_DCMI),
    PE6_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_6, AF_EVENTOUT),

    PE7_REQ_FSMC_D4         = AF_REQ_ENCODE(PORT_E, PIN_7, AF_FSMC),
    PE7_REQ_TIM1_ETR        = AF_REQ_ENCODE(PORT_E, PIN_7, AF_TIM1),
    PE7_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_7, AF_EVENTOUT),

    PE8_REQ_FSMC_D5         = AF_REQ_ENCODE(PORT_E, PIN_8, AF_FSMC),
    PE8_REQ_TIM1_CH1N       = AF_REQ_ENCODE(PORT_E, PIN_8, AF_TIM1),
    PE8_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_8, AF_EVENTOUT),

    PE9_REQ_FSMC_D6         = AF_REQ_ENCODE(PORT_E, PIN_9, AF_FSMC),
    PE9_REQ_TIM1_CH1        = AF_REQ_ENCODE(PORT_E, PIN_9, AF_TIM1),
    PE9_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_9, AF_EVENTOUT),

    PE10_REQ_FSMC_D7        = AF_REQ_ENCODE(PORT_E, PIN_10, AF_FSMC),
    PE10_REQ_TIM1_CH2N      = AF_REQ_ENCODE(PORT_E, PIN_10, AF_TIM1),
    PE10_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_E, PIN_10, AF_EVENTOUT),

    PE11_REQ_FSMC_D8         = AF_REQ_ENCODE(PORT_E, PIN_11, AF_FSMC),
    PE11_REQ_TIM1_CH2        = AF_REQ_ENCODE(PORT_E, PIN_11, AF_TIM1),
    PE11_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_11, AF_EVENTOUT),

    PE12_REQ_FSMC_D9         = AF_REQ_ENCODE(PORT_E, PIN_12, AF_FSMC),
    PE12_REQ_TIM1_CH3N       = AF_REQ_ENCODE(PORT_E, PIN_12, AF_TIM1),
    PE12_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_12, AF_EVENTOUT),

    PE13_REQ_FSMC_D10        = AF_REQ_ENCODE(PORT_E, PIN_13, AF_FSMC),
    PE13_REQ_TIM1_CH3        = AF_REQ_ENCODE(PORT_E, PIN_13, AF_TIM1),
    PE13_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_13, AF_EVENTOUT),

    PE14_REQ_FSMC_D11        = AF_REQ_ENCODE(PORT_E, PIN_14, AF_FSMC),
    PE14_REQ_TIM1_CH4        = AF_REQ_ENCODE(PORT_E, PIN_14, AF_TIM1),
    PE14_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_14, AF_EVENTOUT),

    PE15_REQ_FSMC_D12        = AF_REQ_ENCODE(PORT_E, PIN_15, AF_FSMC),
    PE15_REQ_TIM1_BKIN       = AF_REQ_ENCODE(PORT_E, PIN_15, AF_TIM1),
    PE15_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_E, PIN_15, AF_EVENTOUT),

    PF0_REQ_FSMC_A0         = AF_REQ_ENCODE(PORT_F, PIN_0, AF_FSMC),
    PF0_REQ_I2C2_SDA        = AF_REQ_ENCODE(PORT_F, PIN_0, AF_I2C2),
    PF0_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_F, PIN_0, AF_EVENTOUT),

    PF1_REQ_FSMC_A1         = AF_REQ_ENCODE(PORT_F, PIN_1, AF_FSMC),
    PF1_REQ_I2C2_SCL        = AF_REQ_ENCODE(PORT_F, PIN_1, AF_I2C2),
    PF1_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_F, PIN_1, AF_EVENTOUT),

    PF2_REQ_FSMC_A2         = AF_REQ_ENCODE(PORT_F, PIN_2, AF_FSMC),
    PF2_REQ_I2C2_SMBA       = AF_REQ_ENCODE(PORT_F, PIN_2, AF_I2C2),
    PF2_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_F, PIN_2, AF_EVENTOUT),

    PF3_REQ_FSMC_A3         = AF_REQ_ENCODE(PORT_F, PIN_3, AF_FSMC),
    PF3_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_F, PIN_3, AF_EVENTOUT),

    PF4_REQ_FSMC_A4         = AF_REQ_ENCODE(PORT_F, PIN_4, AF_FSMC),
    PF4_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_F, PIN_4, AF_EVENTOUT),

    PF5_REQ_FSMC_A5         = AF_REQ_ENCODE(PORT_F, PIN_5, AF_FSMC),
    PF5_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_F, PIN_5, AF_EVENTOUT),

    PF6_REQ_TIM10_CH1       = AF_REQ_ENCODE(PORT_F, PIN_6, AF_TIM10),
    PF6_REQ_FSMC_NIORD      = AF_REQ_ENCODE(PORT_F, PIN_6, AF_FSMC),
    PF6_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_F, PIN_6, AF_EVENTOUT),

    PF7_REQ_TIM11_CH1       = AF_REQ_ENCODE(PORT_F, PIN_7, AF_TIM11),
    PF7_REQ_FSMC_NREG       = AF_REQ_ENCODE(PORT_F, PIN_7, AF_FSMC),
    PF7_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_F, PIN_7, AF_EVENTOUT),

    PF8_REQ_TIM13_CH1       = AF_REQ_ENCODE(PORT_F, PIN_8, AF_TIM13),
    PF8_REQ_FSMC_NIOWR      = AF_REQ_ENCODE(PORT_F, PIN_8, AF_FSMC),
    PF8_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_F, PIN_8, AF_EVENTOUT),

    PF9_REQ_TIM14_CH1       = AF_REQ_ENCODE(PORT_F, PIN_9, AF_TIM14),
    PF9_REQ_FSMC_CD         = AF_REQ_ENCODE(PORT_F, PIN_9, AF_FSMC),
    PF9_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_F, PIN_9, AF_EVENTOUT),

    PF10_REQ_FSMC_INTR      = AF_REQ_ENCODE(PORT_F, PIN_10, AF_FSMC),
    PF10_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_F, PIN_10, AF_EVENTOUT),

    PF11_REQ_DCMI_D12       = AF_REQ_ENCODE(PORT_F, PIN_11, AF_DCMI),
    PF11_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_F, PIN_11, AF_EVENTOUT),

    PF12_REQ_FSMC_A6        = AF_REQ_ENCODE(PORT_F, PIN_12, AF_FSMC),
    PF12_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_F, PIN_12, AF_EVENTOUT),

    PF13_REQ_FSMC_A7        = AF_REQ_ENCODE(PORT_F, PIN_13, AF_FSMC),
    PF13_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_F, PIN_13, AF_EVENTOUT),

    PF14_REQ_FSMC_A8        = AF_REQ_ENCODE(PORT_F, PIN_14, AF_FSMC),
    PF14_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_F, PIN_14, AF_EVENTOUT),

    PF15_REQ_FSMC_A9        = AF_REQ_ENCODE(PORT_F, PIN_15, AF_FSMC),
    PF15_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_F, PIN_15, AF_EVENTOUT),

    PG0_REQ_FSMC_A10        = AF_REQ_ENCODE(PORT_G, PIN_0, AF_FSMC),
    PG0_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_G, PIN_0, AF_EVENTOUT),

    PG1_REQ_FSMC_A11        = AF_REQ_ENCODE(PORT_G, PIN_1, AF_FSMC),
    PG1_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_G, PIN_1, AF_EVENTOUT),

    PG2_REQ_FSMC_A12        = AF_REQ_ENCODE(PORT_G, PIN_2, AF_FSMC),
    PG2_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_G, PIN_2, AF_EVENTOUT),

    PG3_REQ_FSMC_A13        = AF_REQ_ENCODE(PORT_G, PIN_3, AF_FSMC),
    PG3_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_G, PIN_3, AF_EVENTOUT),

    PG4_REQ_FSMC_A14        = AF_REQ_ENCODE(PORT_G, PIN_4, AF_FSMC),
    PG4_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_G, PIN_4, AF_EVENTOUT),

    PG5_REQ_FSMC_A15        = AF_REQ_ENCODE(PORT_G, PIN_5, AF_FSMC),
    PG5_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_G, PIN_5, AF_EVENTOUT),

    PG6_REQ_FSMC_INT2       = AF_REQ_ENCODE(PORT_G, PIN_6, AF_FSMC),
    PG6_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_G, PIN_6, AF_EVENTOUT),

    PG7_REQ_FSMC_INT3       = AF_REQ_ENCODE(PORT_G, PIN_7, AF_FSMC),
    PG7_REQ_USART6_CK       = AF_REQ_ENCODE(PORT_G, PIN_7, AF_USART6),
    PG7_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_G, PIN_7, AF_EVENTOUT),

    PG8_REQ_USART6_RTS      = AF_REQ_ENCODE(PORT_G, PIN_8, AF_USART6),
    PG8_REQ_ETH_PPS_OUT     = AF_REQ_ENCODE(PORT_G, PIN_8, AF_ETH),
    PG8_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_G, PIN_8, AF_EVENTOUT),

    PG9_REQ_USART6_RX       = AF_REQ_ENCODE(PORT_G, PIN_9, AF_USART6),
    PG9_REQ_FSMC_NE2        = AF_REQ_ENCODE(PORT_G, PIN_9, AF_FSMC),
    PG9_REQ_FSMC_NCE3       = AF_REQ_ENCODE(PORT_G, PIN_9, AF_FSMC),
    PG9_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_G, PIN_9, AF_EVENTOUT),

    PG10_REQ_FSMC_NCE4_1    = AF_REQ_ENCODE(PORT_G, PIN_10, AF_FSMC),
    PG10_REQ_FSMC_NE3       = AF_REQ_ENCODE(PORT_G, PIN_10, AF_FSMC),
    PG10_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_G, PIN_10, AF_EVENTOUT),

    PG11_REQ_FSMC_NCE4_2    = AF_REQ_ENCODE(PORT_G, PIN_11, AF_FSMC),
    PG11_REQ_ETH_MII_TX_EN  = AF_REQ_ENCODE(PORT_G, PIN_11, AF_ETH),
    PG11_REQ_ETH_RMII_TX_EN = AF_REQ_ENCODE(PORT_G, PIN_11, AF_ETH),
    PG11_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_G, PIN_11, AF_EVENTOUT),

    PG12_REQ_FSMC_NE4       = AF_REQ_ENCODE(PORT_G, PIN_12, AF_FSMC),
    PG12_REQ_USART6_RTS     = AF_REQ_ENCODE(PORT_G, PIN_12, AF_USART6),
    PG12_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_G, PIN_12, AF_EVENTOUT),

    PG13_REQ_FSMC_A24       = AF_REQ_ENCODE(PORT_G, PIN_13, AF_FSMC),
    PG13_REQ_USART6_CTS     = AF_REQ_ENCODE(PORT_G, PIN_13, AF_USART6),
    PG13_REQ_ETH_MII_TXD0   = AF_REQ_ENCODE(PORT_G, PIN_13, AF_ETH),
    PG13_REQ_ETH_RMII_TXD0  = AF_REQ_ENCODE(PORT_G, PIN_13, AF_ETH),
    PG13_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_G, PIN_13, AF_EVENTOUT),

    PG14_REQ_FSMC_A25       = AF_REQ_ENCODE(PORT_G, PIN_14, AF_FSMC),
    PG14_REQ_USART6_TX      = AF_REQ_ENCODE(PORT_G, PIN_14, AF_USART6),
    PG14_REQ_ETH_MII_TXD1   = AF_REQ_ENCODE(PORT_G, PIN_14, AF_ETH),
    PG14_REQ_ETH_RMII_TXD1  = AF_REQ_ENCODE(PORT_G, PIN_14, AF_ETH),
    PG14_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_G, PIN_14, AF_EVENTOUT),

    PG15_REQ_USART6_CTS     = AF_REQ_ENCODE(PORT_G, PIN_15, AF_USART6),
    PG15_REQ_DCMI_D13       = AF_REQ_ENCODE(PORT_G, PIN_15, AF_DCMI),
    PG15_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_G, PIN_15, AF_EVENTOUT),

    PH0_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_H, PIN_0, AF_EVENTOUT),

    PH1_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_H, PIN_1, AF_EVENTOUT),

    PH2_REQ_ETH_MII_CRS     = AF_REQ_ENCODE(PORT_H, PIN_2, AF_ETH),
    PH2_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_H, PIN_2, AF_EVENTOUT),

    PH3_REQ_ETH_MII_COL     = AF_REQ_ENCODE(PORT_H, PIN_3, AF_ETH),
    PH3_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_H, PIN_3, AF_EVENTOUT),

    PH4_REQ_I2C2_SCL        = AF_REQ_ENCODE(PORT_H, PIN_4, AF_I2C2),
    PH4_REQ_OTG_HS_ULPI_NXT = AF_REQ_ENCODE(PORT_H, PIN_4, AF_OTG_HS),
    PH4_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_H, PIN_4, AF_EVENTOUT),

    PH5_REQ_I2C2_SDA        = AF_REQ_ENCODE(PORT_H, PIN_5, AF_I2C2),
    PH5_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_H, PIN_5, AF_EVENTOUT),

    PH6_REQ_I2C2_SMBA       = AF_REQ_ENCODE(PORT_H, PIN_6, AF_I2C2),
    PH6_REQ_TIM12_CH1       = AF_REQ_ENCODE(PORT_H, PIN_6, AF_TIM12),
    PH6_REQ_ETH_MII_RXD2    = AF_REQ_ENCODE(PORT_H, PIN_6, AF_ETH),
    PH6_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_H, PIN_6, AF_EVENTOUT),

    PH7_REQ_I2C3_SCL        = AF_REQ_ENCODE(PORT_H, PIN_7, AF_I2C3),
    PH7_REQ_ETH_MII_RXD3    = AF_REQ_ENCODE(PORT_H, PIN_7, AF_ETH),
    PH7_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_H, PIN_7, AF_EVENTOUT),

    PH8_REQ_I2C3_SDA        = AF_REQ_ENCODE(PORT_H, PIN_8, AF_I2C3),
    PH8_REQ_DCMI_HSYNC      = AF_REQ_ENCODE(PORT_H, PIN_8, AF_DCMI),
    PH8_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_H, PIN_8, AF_EVENTOUT),

    PH9_REQ_I2C3_SMBA       = AF_REQ_ENCODE(PORT_H, PIN_9, AF_I2C3),
    PH9_REQ_TIM12_CH2       = AF_REQ_ENCODE(PORT_H, PIN_9, AF_TIM12),
    PH9_REQ_DCMI_D0         = AF_REQ_ENCODE(PORT_H, PIN_9, AF_DCMI),
    PH9_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_H, PIN_9, AF_EVENTOUT),

    PH10_REQ_TIM5_CH1       = AF_REQ_ENCODE(PORT_H, PIN_10, AF_TIM5),
    PH10_REQ_DCMI_D1        = AF_REQ_ENCODE(PORT_H, PIN_10, AF_DCMI),
    PH10_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_H, PIN_10, AF_EVENTOUT),

    PH11_REQ_TIM5_CH2       = AF_REQ_ENCODE(PORT_H, PIN_11, AF_TIM5),
    PH11_REQ_DCMI_D2        = AF_REQ_ENCODE(PORT_H, PIN_11, AF_DCMI),
    PH11_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_H, PIN_11, AF_EVENTOUT),

    PH12_REQ_TIM5_CH3       = AF_REQ_ENCODE(PORT_H, PIN_12, AF_TIM5),
    PH12_REQ_DCMI_D3        = AF_REQ_ENCODE(PORT_H, PIN_12, AF_DCMI),
    PH12_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_H, PIN_12, AF_EVENTOUT),

    PH13_REQ_TIM8_CH1N      = AF_REQ_ENCODE(PORT_H, PIN_13, AF_TIM8),
    PH13_REQ_CAN1_TX        = AF_REQ_ENCODE(PORT_H, PIN_13, AF_CAN1),
    PH13_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_H, PIN_13, AF_EVENTOUT),

    PH14_REQ_TIM8_CH2N      = AF_REQ_ENCODE(PORT_H, PIN_14, AF_TIM8),
    PH14_REQ_DCMI_D4        = AF_REQ_ENCODE(PORT_H, PIN_14, AF_DCMI),
    PH14_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_H, PIN_14, AF_EVENTOUT),

    PH15_REQ_TIM8_CH3N       = AF_REQ_ENCODE(PORT_H, PIN_15, AF_TIM8),
    PH15_REQ_DCMI_D11        = AF_REQ_ENCODE(PORT_H, PIN_15, AF_DCMI),
    PH15_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_H, PIN_15, AF_EVENTOUT),

    PI0_REQ_TIM5_CH4         = AF_REQ_ENCODE(PORT_I, PIN_0, AF_TIM5),
    PI0_REQ_SPI2_NSS         = AF_REQ_ENCODE(PORT_I, PIN_0, AF_SPI2),
    PI0_REQ_I2S2_WS          = AF_REQ_ENCODE(PORT_I, PIN_0, AF_I2S2),
    PI0_REQ_DCMI_D13         = AF_REQ_ENCODE(PORT_I, PIN_0, AF_DCMI),
    PI0_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_I, PIN_0, AF_EVENTOUT),

    PI1_REQ_SPI2_SCK         = AF_REQ_ENCODE(PORT_I, PIN_1, AF_SPI2),
    PI1_REQ_I2S2_CK          = AF_REQ_ENCODE(PORT_I, PIN_1, AF_I2S2),
    PI1_REQ_DCMI_D8          = AF_REQ_ENCODE(PORT_I, PIN_1, AF_DCMI),
    PI1_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_I, PIN_1, AF_EVENTOUT),

    PI2_REQ_TIM8_CH4         = AF_REQ_ENCODE(PORT_I, PIN_2, AF_TIM8),
    PI2_REQ_SPI2_MISO        = AF_REQ_ENCODE(PORT_I, PIN_2, AF_SPI2),
    PI2_REQ_DCMI_D9          = AF_REQ_ENCODE(PORT_I, PIN_2, AF_DCMI),
    PI2_REQ_I2S2ext_SD       = AF_REQ_ENCODE(PORT_I, PIN_2, AF_I2S2),
    PI2_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_I, PIN_2, AF_EVENTOUT),

    PI3_REQ_TIM8_ETR         = AF_REQ_ENCODE(PORT_I, PIN_3, AF_TIM8),
    PI3_REQ_SPI2_MOSI        = AF_REQ_ENCODE(PORT_I, PIN_3, AF_SPI2),
    PI3_REQ_I2S2_SD          = AF_REQ_ENCODE(PORT_I, PIN_3, AF_I2S2),
    PI3_REQ_DCMI_D10         = AF_REQ_ENCODE(PORT_I, PIN_3, AF_DCMI),
    PI3_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_I, PIN_3, AF_EVENTOUT),

    PI4_REQ_TIM8_BKIN        = AF_REQ_ENCODE(PORT_I, PIN_4, AF_TIM8),
    PI4_REQ_DCMI_D5          = AF_REQ_ENCODE(PORT_I, PIN_4, AF_DCMI),
    PI4_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_I, PIN_4, AF_EVENTOUT),

    PI5_REQ_TIM8_CH1         = AF_REQ_ENCODE(PORT_I, PIN_5, AF_TIM8),
    PI5_REQ_DCMI_VSYNC       = AF_REQ_ENCODE(PORT_I, PIN_5, AF_DCMI),
    PI5_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_I, PIN_5, AF_EVENTOUT),

    PI6_REQ_TIM8_CH2         = AF_REQ_ENCODE(PORT_I, PIN_6, AF_TIM8),
    PI6_REQ_DCMI_D6          = AF_REQ_ENCODE(PORT_I, PIN_6, AF_DCMI),
    PI6_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_I, PIN_6, AF_EVENTOUT),

    PI7_REQ_TIM8_CH3         = AF_REQ_ENCODE(PORT_I, PIN_7, AF_TIM8),
    PI7_REQ_DCMI_D7          = AF_REQ_ENCODE(PORT_I, PIN_7, AF_DCMI),
    PI7_REQ_EVENT_OUT        = AF_REQ_ENCODE(PORT_I, PIN_7, AF_EVENTOUT),

    //PI8 no AF

    PI9_REQ_CAN1_RX         = AF_REQ_ENCODE(PORT_I, PIN_9, AF_CAN1),
    PI9_REQ_EVENT_OUT       = AF_REQ_ENCODE(PORT_I, PIN_9, AF_EVENTOUT),

    PI10_REQ_ETH_MII_RX_ER  = AF_REQ_ENCODE(PORT_I, PIN_10, AF_ETH),
    PI10_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_I, PIN_10, AF_EVENTOUT),

    PI11_REQ_OTG_HS_ULPI_DIR  = AF_REQ_ENCODE(PORT_I, PIN_11, AF_OTG_HS),
    PI11_REQ_EVENT_OUT      = AF_REQ_ENCODE(PORT_I, PIN_11, AF_EVENTOUT),

} pin_af;

/* 上下拉 */
typedef enum : uint8_t {
    PIN_PUPD_NONE = 0,
    PIN_PUPD_PULLUP,
    PIN_PUPD_PULLDOWN,
} pin_pupd;

/* 新增：中断触发类型 */
typedef enum : uint8_t {
    PIN_IRQ_MODE_NONE = 0,  // 无中断
    PIN_IRQ_MODE_RISING,    // 上升沿
    PIN_IRQ_MODE_FALLING,   // 下降沿
    PIN_IRQ_MODE_BOTH       // 双边沿
} exti_mode;


/* ---------- 寄存器定义（仅需用到的部分） ---------- */
typedef struct {
    volatile uint32_t MODER;
    volatile uint32_t OTYPER;
    volatile uint32_t OSPEEDR;
    volatile uint32_t PUPDR;
    volatile uint32_t IDR;
    volatile uint32_t ODR;
    volatile uint32_t BSRR;
    volatile uint32_t LCKR;
    volatile uint32_t AFRL;    /* 偏移 0x20, 引脚 0..7 */
    volatile uint32_t AFRH;    /* 偏移 0x24, 引脚 8..15 */
} xGPIO_TypeDef;

/* SYSCFG 基地址 */
#define xSYSCFG_BASE 0x40013800UL
typedef struct {
    volatile uint32_t MEMRMP;
    volatile uint32_t PMC;
    volatile uint32_t EXTICR[4];   // 四个寄存器，每个管理4个EXTI线
    // ... 其他寄存器忽略
} xSYSCFG_TypeDef;
#define xSYSCFG ((xSYSCFG_TypeDef*)xSYSCFG_BASE)

extern xGPIO_TypeDef* const GPIOx[];


void hal_gpio_clock_enable(gpio_port_t port);
void hal_gpio_set_mode(xGPIO_TypeDef *gpiox, uint8_t pin, pin_mode mode);
void hal_gpio_set_af(xGPIO_TypeDef *gpiox, uint8_t pin, uint8_t af);
void hal_gpio_set_otype(xGPIO_TypeDef *gpiox, uint8_t pin, pin_otype otype);
void hal_gpio_set_ospeed(xGPIO_TypeDef *gpiox, uint8_t pin, pin_ospeed ospeed);
void hal_gpio_set_pupd(xGPIO_TypeDef *gpiox, uint8_t pin, pin_pupd pupd);
#endif //STM32F4DISCOVERY_HAL_GPIO_H
